### ISSUE TITLE
About your paper

### ISSUE THREAD

**Issue by Lonicer** [IMCCretrieval/MomentDiff#1]
Hello, where does the C3D feature in the Charades-STA dataset in your paper come from? I see that the feature comparison in VSLNet is as follows, and the I3D feature should be used:
your:
![image](https://github.com/IMCCretrieval/MomentDiff/assets/70836946/68b90ae3-0d0e-4fa7-adfa-653e99451e01)

VSLNet:
![image](https://github.com/IMCCretrieval/MomentDiff/assets/70836946/e2d4f8f4-2c05-4060-aa16-8642f2888d2b)
so is the feature used for your model comparison performance I3D or C3D?

**Comment by IMCCretrieval** [comment]
Thank you for your concern, the C3D features we use can be extracted according to the instructions [here](https://github.com/26hzhang/VSLNet/tree/master/prepare).

**Comment by IMCCretrieval** [comment]
Thank you for your concern, the features can be extracted according to [VSLNet](https://github.com/26hzhang/VSLNet/tree/master/prepare) [Paper](https://arxiv.org/pdf/2004.13931v1.pdf).
