### ISSUE TITLE
About the scripts of QVHighlights and TACoS

### ISSUE THREAD

**Issue by TensorsSun** [IMCCretrieval/MomentDiff#4]
Hi, could you provide script files of QVHighlights and TACoS? The parameters on different datasets seem to be slightly different.

**Comment by JonnyS1226** [comment]
Appreciate for the good work.
But I have the same question. I use the similar config to train on QVHighlights, but can only get around 32 mAP where the reported one is 35.95.

**Comment by aa7784171** [comment]
Hi, could you provide script files of QVHighlights? Thanks.

**Comment by IMCCretrieval** [comment]
> Appreciate for the good work. But I have the same question. I use the similar config to train on QVHighlights, but can only get around 32 mAP where the reported one is 35.95.

Thank you for your attention. In the code trained on the QVHighlights and TACOS datasets, these codes need to be uncommented:
line 320- 323 in https://github.com/IMCCretrieval/MomentDiff/blob/main/momentdiff/model.py .
You can also adjust the loss coefficient (0.1 or other numbers ) in loss_bce to get better results.

**Comment by IMCCretrieval** [comment]
> Hi, could you provide script files of QVHighlights? Thanks.

Thank you for your attention. I'm sorry that due to personal resignation, more files were lost in the previous company server. You can refer to this issue (https://github.com/IMCCretrieval/MomentDiff/issues/3) for parameter settings.

**Comment by YunjinYeung** [comment]
Hi! When I completed the process of reproduce QVHighlight according to the help of the issue, I have set the `loss_bce` parameter to `0.1` 
![image](https://github.com/IMCCretrieval/MomentDiff/assets/158540303/e22140c5-83f1-44f9-b6d3-e60247f8aba5)
and `lr_rate` to `0.0001`, and set both `span_loss_coef` and `set_cost_span` to `10`. But unfortunately, the best result of "`MR-full-R1@0.5`" is `50.84`, which is far from the result of your paper. This is my opt.json file, 
[opt.json.zip](https://github.com/IMCCretrieval/MomentDiff/files/14414750/opt.json.zip)
can you tell me what else the important parameters should I adjust?

**Comment by IMCCretrieval** [comment]
> Hi! When I completed the process of reproduce QVHighlight according to the help of the issue, I have set the `loss_bce` parameter to `0.1` ![image](https://private-user-images.githubusercontent.com/158540303/308048064-e22140c5-83f1-44f9-b6d3-e60247f8aba5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODYwNzksIm5iZiI6MTcwOTA4NTc3OSwicGF0aCI6Ii8xNTg1NDAzMDMvMzA4MDQ4MDY0LWUyMjE0MGM1LTgzZjEtNDRmOS1iNmQzLWU2MDI0N2Y4YWJhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQwMjAyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWY3ZTBkMmQ1ZTdkYTA1MzRiMTdiNDdlYWVhNmM4OWU4MDNiZmZjNTRmMzlkYmZkMjU5OWFhODA0NWZjYTM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ykQIUttuzTcrKcZqn8dXYoy3eqtmOchZQx8CvlxB5qw) and `lr_rate` to `0.0001`, and set both `span_loss_coef` and `set_cost_span` to `10`. But unfortunately, the best result of "`MR-full-R1@0.5`" is `50.84`, which is far from the result of your paper. This is my opt.json file, [opt.json.zip](https://github.com/IMCCretrieval/MomentDiff/files/14414750/opt.json.zip) can you tell me what else the important parameters should I adjust?

Thanks for your question.
In my experiments, I remember that carefully adjusting the loss_sim function (https://github.com/IMCCretrieval/MomentDiff/blob/main/momentdiff/model.py.) can achieve MR-full-R1@0.5 **59.3** on val.
My suggestion is that you can adjust this function according to the code of QD-DETR.

**Comment by YunjinYeung** [comment]
Hi, could you provide script files or config files of  TACoS? Thanks

**Comment by Song200103** [comment]
Hi, could you provide script files or config files of TACoS? Thanks
